name: Build iOS Simulator App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        # Upgraded from v3 to v4
        uses: actions/checkout@v4

      - name: Compile Simulator App
        run: |
          cd TrafficRacer.swiftpm
          
          xcodebuild -destination "platform=iOS Simulator,name=iPhone 15" \
                     -scheme TrafficRacer \
                     -configuration Release \
                     -archivePath "$GITHUB_WORKSPACE/build/TrafficRacer.xcarchive" \
                     archive \
                     CODE_SIGNING_ALLOWED=NO

      - name: Package for Appetize Simulator
        run: |
          mkdir -p "$GITHUB_WORKSPACE/Payload"
          cp -r "$GITHUB_WORKSPACE/build/TrafficRacer.xcarchive/Products/Applications/TrafficRacer.app" "$GITHUB_WORKSPACE/Payload/"
          cd "$GITHUB_WORKSPACE"
          zip -r TrafficRacerSimulator.zip Payload

      - name: Upload Simulator Zip
        # Upgraded from v3 to v4
        uses: actions/upload-artifact@v4
        with:
          name: Simulator-Build
          path: TrafficRacerSimulator.zip
